# Generated by Django 4.1.6 on 2023-02-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_products',
            field=models.ManyToManyField(blank=True, to='app.product'),
        ),
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
